workflows:
  ios-release:
    name: iOS Release

    environment:
      flutter: stable

    scripts:
      - name: Flutter doctor
        script: |
          flutter doctor

      - name: Flutter clean
        script: |
          flutter clean

      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Precache iOS artifacts
        script: |
          flutter precache --ios

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa